/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.core1;

import java.math.BigDecimal;
import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.JSType.toInteger;
import main.SubModules;
import main.entities.Address;
import main.entities.Contact;
import main.entities.ContactPerson;
import main.entities.Doctor;
import main.entities.Patient;
import main.entities.Insurance;

/**
 *
 * @author DelaTorreNelson
 */
public class Registration extends javax.swing.JFrame {  
    
    /**
     * Creates new form registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp_gender = new javax.swing.ButtonGroup();
        btnGrp_relationshipToPatient_1 = new javax.swing.ButtonGroup();
        btnGrp_relationshipToPatient_2 = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        window_control = new javax.swing.JPanel();
        btn_back = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        admin_level = new javax.swing.JLabel();
        admin_name = new javax.swing.JLabel();
        subModuleHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        body = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        pnl_personalInfo3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_firstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_lastname = new javax.swing.JTextField();
        tf_middlename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_birthplace = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rb_mixed = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();
        rb_male = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cmbx_civilStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jd_birthdate = new com.toedter.calendar.JDateChooser();
        sp_age = new javax.swing.JSpinner();
        tf_occupation = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_nationality = new javax.swing.JTextField();
        pnl_insurance_info = new javax.swing.JPanel();
        pnl_primary = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jd_insured_birthdate = new com.toedter.calendar.JDateChooser();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tf_insured_middlename = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tf_insured_lastname = new javax.swing.JTextField();
        rb_self = new javax.swing.JRadioButton();
        rb_child = new javax.swing.JRadioButton();
        rb_other = new javax.swing.JRadioButton();
        tf_insured_name = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rb_spouse = new javax.swing.JRadioButton();
        tf_specify = new javax.swing.JTextField();
        lbl_specify = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sp_remaining = new javax.swing.JSpinner();
        tf_insurance_id = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        tf_insurance_company = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tf_insurance_address = new javax.swing.JTextField();
        tf_insurance_municipality = new javax.swing.JTextField();
        tf_insurance_city = new javax.swing.JTextField();
        tf_insurance_zip = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        tf_insurance_no = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pnl_address = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tf_lot = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        tf_municipality = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_city = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_zip = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        pnl_contact = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tf_telephone = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_cellphone = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        pnl_contact_person = new javax.swing.JPanel();
        tf_contact_person_firstname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_contact_person_lastname = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tf_contact_person_middlename = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_contact_person_relation = new javax.swing.JTextField();
        tf_contact_person_contact = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        pnl_government_mandated = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        tf_philhealth = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        tf_sss = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        tf_gsis = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Registration");
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setUndecorated(true);
        setResizable(false);

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setMaximumSize(new java.awt.Dimension(1024, 80));
        header.setMinimumSize(new java.awt.Dimension(1024, 80));
        header.setPreferredSize(new java.awt.Dimension(1024, 110));

        window_control.setOpaque(false);
        window_control.setLayout(new java.awt.GridLayout(1, 0));

        btn_back.setText("<");
        btn_back.setFocusable(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        window_control.add(btn_back);

        btn_close.setText("X");
        btn_close.setFocusable(false);
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        window_control.add(btn_close);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/logo_227x104.png"))); // NOI18N

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        admin_level.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(admin_level);

        admin_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin_name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(admin_name);

        subModuleHeader.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        subModuleHeader.setText("Registration");
        subModuleHeader.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(window_control, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addComponent(subModuleHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(window_control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(subModuleHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setMaximumSize(new java.awt.Dimension(950, 400));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(950, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(950, 400));

        body.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        body.setAutoscrolls(true);
        body.setMaximumSize(new java.awt.Dimension(900, 1400));
        body.setMinimumSize(new java.awt.Dimension(900, 1400));
        body.setPreferredSize(new java.awt.Dimension(900, 1400));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("<html>\n<body style=\"padding: 4px;\">\n<h3>DATA PRIVACY ACT of 2012</h3>\n<p>\nIn compliance to R.A. 10173, any information that is given to this system\nshall remain confidencial\nand nothing will be publicized,\nunless it is required by the law.\n</p>\n</body>\n</html>");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "R.A. 10173", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16))); // NOI18N
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        pnl_personalInfo3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16), java.awt.Color.darkGray)); // NOI18N
        pnl_personalInfo3.setForeground(java.awt.Color.darkGray);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setForeground(java.awt.Color.darkGray);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("First Name:");

        tf_firstname.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_firstname.setForeground(java.awt.Color.darkGray);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(java.awt.Color.darkGray);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Last Name:");

        tf_lastname.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_lastname.setForeground(java.awt.Color.darkGray);

        tf_middlename.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_middlename.setForeground(java.awt.Color.darkGray);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(java.awt.Color.darkGray);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Middlename:");

        tf_birthplace.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_birthplace.setForeground(java.awt.Color.darkGray);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(java.awt.Color.darkGray);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Birthplace:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(java.awt.Color.darkGray);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Gender:");

        btnGrp_gender.add(rb_mixed);
        rb_mixed.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rb_mixed.setForeground(java.awt.Color.darkGray);
        rb_mixed.setText("Mixed");
        rb_mixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_mixedActionPerformed(evt);
            }
        });

        btnGrp_gender.add(rb_female);
        rb_female.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rb_female.setForeground(java.awt.Color.darkGray);
        rb_female.setText("Female");
        rb_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_femaleActionPerformed(evt);
            }
        });

        btnGrp_gender.add(rb_male);
        rb_male.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rb_male.setForeground(java.awt.Color.darkGray);
        rb_male.setText("Male");
        rb_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_maleActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(java.awt.Color.darkGray);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Civil Status:");

        cmbx_civilStatus.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        cmbx_civilStatus.setForeground(java.awt.Color.darkGray);
        cmbx_civilStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", "Separated", "Widowed" }));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setForeground(java.awt.Color.darkGray);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Birthdate:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setForeground(java.awt.Color.darkGray);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Age:");

        jd_birthdate.setForeground(java.awt.Color.darkGray);
        jd_birthdate.setDateFormatString("yyyy-MM-dd");
        jd_birthdate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        sp_age.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        sp_age.setModel(new javax.swing.SpinnerNumberModel(0, 0, 150, 1));

        tf_occupation.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_occupation.setForeground(java.awt.Color.darkGray);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel12.setForeground(java.awt.Color.darkGray);
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Occupation:");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel16.setForeground(java.awt.Color.darkGray);
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Nationality:");

        tf_nationality.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_nationality.setForeground(java.awt.Color.darkGray);

        javax.swing.GroupLayout pnl_personalInfo3Layout = new javax.swing.GroupLayout(pnl_personalInfo3);
        pnl_personalInfo3.setLayout(pnl_personalInfo3Layout);
        pnl_personalInfo3Layout.setHorizontalGroup(
            pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personalInfo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_personalInfo3Layout.createSequentialGroup()
                        .addComponent(rb_female)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_mixed))
                    .addComponent(tf_birthplace, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_middlename, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbx_civilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jd_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_age, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(tf_lastname))
                .addContainerGap())
        );

        pnl_personalInfo3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbx_civilStatus, jd_birthdate, sp_age, tf_birthplace, tf_firstname, tf_lastname, tf_middlename, tf_nationality, tf_occupation});

        pnl_personalInfo3Layout.setVerticalGroup(
            pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personalInfo3Layout.createSequentialGroup()
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(tf_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(tf_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(tf_middlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(tf_birthplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(tf_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(tf_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jd_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sp_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbx_civilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_personalInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rb_male)
                    .addComponent(rb_female)
                    .addComponent(rb_mixed)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_personalInfo3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbx_civilStatus, jd_birthdate, sp_age, tf_birthplace, tf_firstname, tf_lastname, tf_middlename, tf_nationality, tf_occupation});

        pnl_insurance_info.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Insurance Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16), java.awt.Color.darkGray)); // NOI18N
        pnl_insurance_info.setForeground(java.awt.Color.darkGray);
        pnl_insurance_info.setMaximumSize(new java.awt.Dimension(800, 32767));
        pnl_insurance_info.setPreferredSize(new java.awt.Dimension(998, 986));

        pnl_primary.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Primary Payor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16), java.awt.Color.darkGray)); // NOI18N
        pnl_primary.setForeground(java.awt.Color.darkGray);
        pnl_primary.setMaximumSize(new java.awt.Dimension(900, 600));
        pnl_primary.setMinimumSize(new java.awt.Dimension(900, 600));
        pnl_primary.setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jd_insured_birthdate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel33.setForeground(java.awt.Color.darkGray);
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Lastname:");

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel34.setForeground(java.awt.Color.darkGray);
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("Middlename:");

        tf_insured_middlename.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_insured_middlename.setForeground(java.awt.Color.darkGray);

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel31.setForeground(java.awt.Color.darkGray);
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Relationship:");

        tf_insured_lastname.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_insured_lastname.setForeground(java.awt.Color.darkGray);

        btnGrp_relationshipToPatient_1.add(rb_self);
        rb_self.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rb_self.setText("Self");

        btnGrp_relationshipToPatient_1.add(rb_child);
        rb_child.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rb_child.setText("Child");
        rb_child.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_childActionPerformed(evt);
            }
        });

        btnGrp_relationshipToPatient_1.add(rb_other);
        rb_other.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rb_other.setText("Other");
        rb_other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_otherActionPerformed(evt);
            }
        });

        tf_insured_name.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_insured_name.setForeground(java.awt.Color.darkGray);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel14.setForeground(java.awt.Color.darkGray);
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Insured Birthdate:");

        btnGrp_relationshipToPatient_1.add(rb_spouse);
        rb_spouse.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rb_spouse.setText("Spouse");

        tf_specify.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_specify.setForeground(java.awt.Color.darkGray);
        tf_specify.setEnabled(false);

        lbl_specify.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_specify.setForeground(java.awt.Color.darkGray);
        lbl_specify.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_specify.setText("Specify:");
        lbl_specify.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel13.setForeground(java.awt.Color.darkGray);
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Name of Insured:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_insured_middlename)
                    .addComponent(tf_insured_lastname)
                    .addComponent(tf_insured_name)
                    .addComponent(jd_insured_birthdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(lbl_specify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rb_self)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_spouse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_child)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_other))
                    .addComponent(tf_specify, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel33, jLabel34});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel31, lbl_specify});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel31)
                    .addComponent(rb_self)
                    .addComponent(rb_spouse)
                    .addComponent(rb_child)
                    .addComponent(rb_other)
                    .addComponent(tf_insured_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tf_insured_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_specify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_specify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tf_insured_middlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jd_insured_birthdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel13, jLabel14});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jd_insured_birthdate, tf_insured_lastname});

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMaximumSize(new java.awt.Dimension(100, 32767));

        sp_remaining.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        tf_insurance_id.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_insurance_id.setForeground(java.awt.Color.darkGray);
        tf_insurance_id.setMaximumSize(new java.awt.Dimension(300, 25));
        tf_insurance_id.setMinimumSize(new java.awt.Dimension(300, 25));
        tf_insurance_id.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel38.setForeground(java.awt.Color.darkGray);
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Remaining Benifits:");
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        tf_insurance_company.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_insurance_company.setForeground(java.awt.Color.darkGray);
        tf_insurance_company.setMaximumSize(new java.awt.Dimension(300, 25));
        tf_insurance_company.setMinimumSize(new java.awt.Dimension(300, 25));
        tf_insurance_company.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel36.setForeground(java.awt.Color.darkGray);
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("City:");
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel37.setForeground(java.awt.Color.darkGray);
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Zip:");
        jLabel37.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel57.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel57.setText("Insurance ID:");
        jLabel57.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel30.setForeground(java.awt.Color.darkGray);
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Insurance Company:");
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel32.setForeground(java.awt.Color.darkGray);
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Address:");
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel35.setForeground(java.awt.Color.darkGray);
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("Municipality:");
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        tf_insurance_address.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_insurance_address.setForeground(java.awt.Color.darkGray);
        tf_insurance_address.setMaximumSize(new java.awt.Dimension(300, 25));
        tf_insurance_address.setMinimumSize(new java.awt.Dimension(300, 25));
        tf_insurance_address.setPreferredSize(new java.awt.Dimension(300, 25));

        tf_insurance_municipality.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_insurance_municipality.setForeground(java.awt.Color.darkGray);
        tf_insurance_municipality.setMaximumSize(new java.awt.Dimension(300, 25));
        tf_insurance_municipality.setMinimumSize(new java.awt.Dimension(300, 25));
        tf_insurance_municipality.setPreferredSize(new java.awt.Dimension(300, 25));

        tf_insurance_city.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_insurance_city.setForeground(java.awt.Color.darkGray);
        tf_insurance_city.setMaximumSize(new java.awt.Dimension(300, 25));
        tf_insurance_city.setMinimumSize(new java.awt.Dimension(300, 25));
        tf_insurance_city.setPreferredSize(new java.awt.Dimension(300, 25));

        tf_insurance_zip.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_insurance_zip.setForeground(java.awt.Color.darkGray);
        tf_insurance_zip.setMaximumSize(new java.awt.Dimension(300, 25));
        tf_insurance_zip.setMinimumSize(new java.awt.Dimension(300, 25));
        tf_insurance_zip.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel59.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel59.setText("Insurance ID No:");
        jLabel59.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        tf_insurance_no.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_insurance_no.setForeground(java.awt.Color.darkGray);
        tf_insurance_no.setMaximumSize(new java.awt.Dimension(300, 25));
        tf_insurance_no.setMinimumSize(new java.awt.Dimension(300, 25));
        tf_insurance_no.setPreferredSize(new java.awt.Dimension(300, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_insurance_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_insurance_city, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(tf_insurance_municipality, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_insurance_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel57)
                                    .addComponent(jLabel59))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_insurance_id, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_insurance_no, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_insurance_company, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sp_remaining, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel30, jLabel32, jLabel35, jLabel36, jLabel37, jLabel38, jLabel57, jLabel59});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {sp_remaining, tf_insurance_company});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tf_insurance_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel30)
                    .addComponent(tf_insurance_company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel38)
                    .addComponent(sp_remaining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_insurance_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(tf_insurance_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tf_insurance_municipality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_insurance_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_insurance_zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {sp_remaining, tf_insurance_company});

        javax.swing.GroupLayout pnl_primaryLayout = new javax.swing.GroupLayout(pnl_primary);
        pnl_primary.setLayout(pnl_primaryLayout);
        pnl_primaryLayout.setHorizontalGroup(
            pnl_primaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_primaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_primaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_primaryLayout.setVerticalGroup(
            pnl_primaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_primaryLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("(This is for those patients who are beneficiary of a health insurance policy or a policy holder itself.)");

        javax.swing.GroupLayout pnl_insurance_infoLayout = new javax.swing.GroupLayout(pnl_insurance_info);
        pnl_insurance_info.setLayout(pnl_insurance_infoLayout);
        pnl_insurance_infoLayout.setHorizontalGroup(
            pnl_insurance_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_insurance_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_insurance_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_insurance_infoLayout.createSequentialGroup()
                        .addComponent(pnl_primary, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnl_insurance_infoLayout.setVerticalGroup(
            pnl_insurance_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_insurance_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_primary, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_address.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16), java.awt.Color.darkGray)); // NOI18N
        pnl_address.setForeground(java.awt.Color.darkGray);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel17.setForeground(java.awt.Color.darkGray);
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Lot or House Number:");

        tf_lot.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_lot.setForeground(java.awt.Color.darkGray);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel18.setForeground(java.awt.Color.darkGray);
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Street:");

        jTextField13.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTextField13.setForeground(java.awt.Color.darkGray);

        tf_municipality.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_municipality.setForeground(java.awt.Color.darkGray);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel19.setForeground(java.awt.Color.darkGray);
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Municipality / Barangay:");

        tf_city.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_city.setForeground(java.awt.Color.darkGray);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel20.setForeground(java.awt.Color.darkGray);
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("City / State:");

        tf_zip.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_zip.setForeground(java.awt.Color.darkGray);

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel25.setForeground(java.awt.Color.darkGray);
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Zip code:");

        javax.swing.GroupLayout pnl_addressLayout = new javax.swing.GroupLayout(pnl_address);
        pnl_address.setLayout(pnl_addressLayout);
        pnl_addressLayout.setHorizontalGroup(
            pnl_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_addressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_lot, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(jTextField13)
                    .addComponent(tf_municipality)
                    .addComponent(tf_city)
                    .addComponent(tf_zip))
                .addContainerGap())
        );
        pnl_addressLayout.setVerticalGroup(
            pnl_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_addressLayout.createSequentialGroup()
                .addGroup(pnl_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel17)
                    .addComponent(tf_lot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel18)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel19)
                    .addComponent(tf_municipality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel20)
                    .addComponent(tf_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel25)
                    .addComponent(tf_zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnl_addressLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField13, tf_city, tf_lot, tf_municipality, tf_zip});

        pnl_contact.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Contact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16), java.awt.Color.darkGray)); // NOI18N
        pnl_contact.setForeground(java.awt.Color.darkGray);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel21.setForeground(java.awt.Color.darkGray);
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Telephone number:");

        tf_telephone.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_telephone.setForeground(java.awt.Color.darkGray);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel22.setForeground(java.awt.Color.darkGray);
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Cellphone number:");

        tf_cellphone.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_cellphone.setForeground(java.awt.Color.darkGray);

        tf_email.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_email.setForeground(java.awt.Color.darkGray);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel23.setForeground(java.awt.Color.darkGray);
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Email:");

        javax.swing.GroupLayout pnl_contactLayout = new javax.swing.GroupLayout(pnl_contact);
        pnl_contact.setLayout(pnl_contactLayout);
        pnl_contactLayout.setHorizontalGroup(
            pnl_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_contactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_telephone)
                    .addComponent(tf_cellphone)
                    .addComponent(tf_email, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnl_contactLayout.setVerticalGroup(
            pnl_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contactLayout.createSequentialGroup()
                .addGroup(pnl_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel21)
                    .addComponent(tf_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel22)
                    .addComponent(tf_cellphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel23)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnl_contactLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tf_cellphone, tf_email, tf_telephone});

        pnl_contact_person.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Contact Person", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16), java.awt.Color.darkGray)); // NOI18N
        pnl_contact_person.setForeground(java.awt.Color.darkGray);

        tf_contact_person_firstname.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_contact_person_firstname.setForeground(java.awt.Color.darkGray);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel15.setForeground(java.awt.Color.darkGray);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Firstname:");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel24.setForeground(java.awt.Color.darkGray);
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Lastname:");

        tf_contact_person_lastname.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_contact_person_lastname.setForeground(java.awt.Color.darkGray);

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel26.setForeground(java.awt.Color.darkGray);
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Middlename:");

        tf_contact_person_middlename.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_contact_person_middlename.setForeground(java.awt.Color.darkGray);

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel27.setForeground(java.awt.Color.darkGray);
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Relationship to patient:");

        tf_contact_person_relation.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_contact_person_relation.setForeground(java.awt.Color.darkGray);

        tf_contact_person_contact.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_contact_person_contact.setForeground(java.awt.Color.darkGray);

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel28.setForeground(java.awt.Color.darkGray);
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Contact:");

        javax.swing.GroupLayout pnl_contact_personLayout = new javax.swing.GroupLayout(pnl_contact_person);
        pnl_contact_person.setLayout(pnl_contact_personLayout);
        pnl_contact_personLayout.setHorizontalGroup(
            pnl_contact_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contact_personLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_contact_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_contact_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_contact_person_relation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_contact_person_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_contact_person_middlename, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(tf_contact_person_lastname)
                    .addComponent(tf_contact_person_firstname))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_contact_personLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel24, jLabel26, jLabel27, jLabel28});

        pnl_contact_personLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tf_contact_person_contact, tf_contact_person_firstname, tf_contact_person_lastname, tf_contact_person_middlename, tf_contact_person_relation});

        pnl_contact_personLayout.setVerticalGroup(
            pnl_contact_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contact_personLayout.createSequentialGroup()
                .addGroup(pnl_contact_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_contact_person_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_contact_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_contact_person_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_contact_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_contact_person_middlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_contact_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_contact_person_relation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_contact_personLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_contact_person_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_contact_personLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel15, jLabel24, jLabel26, jLabel27, jLabel28});

        pnl_contact_personLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tf_contact_person_contact, tf_contact_person_firstname, tf_contact_person_lastname, tf_contact_person_middlename, tf_contact_person_relation});

        pnl_government_mandated.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Government Mandated", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16), java.awt.Color.darkGray)); // NOI18N

        jLabel51.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("PhilHealth:");

        tf_philhealth.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tf_philhealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_philhealthActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel52.setText("SSS No.:");

        tf_sss.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jLabel53.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel53.setText("GSIS No.:");

        tf_gsis.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel56.setText("Should be updated at least TWO Months before current date.");

        javax.swing.GroupLayout pnl_government_mandatedLayout = new javax.swing.GroupLayout(pnl_government_mandated);
        pnl_government_mandated.setLayout(pnl_government_mandatedLayout);
        pnl_government_mandatedLayout.setHorizontalGroup(
            pnl_government_mandatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_government_mandatedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_government_mandatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_government_mandatedLayout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addGroup(pnl_government_mandatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addComponent(jLabel53))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_government_mandatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_sss, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_philhealth, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_gsis, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pnl_government_mandatedLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel51, jLabel52, jLabel53});

        pnl_government_mandatedLayout.setVerticalGroup(
            pnl_government_mandatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_government_mandatedLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnl_government_mandatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_philhealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_government_mandatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_sss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_government_mandatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_gsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                        .addComponent(pnl_contact_person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(543, 543, 543))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(pnl_personalInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnl_contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_register)
                            .addComponent(pnl_government_mandated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_insurance_info, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(pnl_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_personalInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnl_contact_person, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnl_government_mandated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_insurance_info, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_register)
                .addGap(243, 243, 243))
        );

        jScrollPane1.setViewportView(body);

        footer.setBackground(new java.awt.Color(255, 255, 255));
        footer.setMaximumSize(new java.awt.Dimension(1024, 30));
        footer.setMinimumSize(new java.awt.Dimension(1024, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Copyright 2018, All Rights reserved to Developers Team.");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(footerLayout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addGap(279, 279, 279)))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
            .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(footerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new main.Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void rb_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_femaleActionPerformed
        //patient.setGender(this.rb_female.getText());
    }//GEN-LAST:event_rb_femaleActionPerformed

    private void rb_otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_otherActionPerformed
        lbl_specify.setEnabled(true);
        tf_specify.setEnabled(true);
    }//GEN-LAST:event_rb_otherActionPerformed

    private void rb_childActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_childActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_childActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        Patient patient = new Patient();
        Address address = new Address();
        Contact contact = new Contact();
        ContactPerson contactPerson = new ContactPerson();
        Insurance insurance = new Insurance();
        
        patient.setFirstname(tf_firstname.getText());
        patient.setLastname(tf_lastname.getText());
        patient.setMiddlename(tf_middlename.getText());
        patient.setBirthplace(tf_birthplace.getText());
        patient.setOccupation(tf_occupation.getText());
        patient.setNationality(tf_nationality.getText());
        patient.setBirthdate((Date) jd_birthdate.getDate());
        patient.setAge((int) sp_age.getModel().getValue());
        patient.setCivilStatus((String) cmbx_civilStatus.getSelectedItem()); 
        patient.setGender(new SubModules().getSelectedRadioButton(btnGrp_gender));
        patient.setPhilhealth(toInteger(tf_philhealth.getText()));
        patient.setSss(toInteger(tf_sss.getText()));
        patient.setGsis(toInteger(tf_gsis.getText()));        
        
        address.setLot(toInteger(tf_lot.getText()));
        address.setStreetNo(toInteger(tf_lot.getText()));
        address.setMunicipality(tf_municipality.getText());
        address.setCity(tf_city.getText());
        address.setZip(toInteger(tf_zip.getText()));
        
        contact.setTelephoneNo(toInteger(tf_telephone.getText()));
        contact.setCellphoneNo(toInteger(tf_cellphone.getText()));
        contact.setEmail(tf_email.getText());
        
        contactPerson.setFirstname(tf_contact_person_firstname.getText());
        contactPerson.setLastname(tf_contact_person_lastname.getText());
        contactPerson.setMiddlename(tf_contact_person_middlename.getText());
        contactPerson.setRelationship(tf_contact_person_relation.getText());       

        insurance.setInsuredFirstname(tf_insured_name.getText());
        insurance.setInsuredLastname(tf_insured_lastname.getText());
        insurance.setInsuredMiddlename(tf_insured_middlename.getText());
        insurance.setInsuredBirthdate((Date) jd_insured_birthdate.getDate());
        
        if(!rb_other.isSelected()){
            insurance.setInsuredRelationship(new SubModules().getSelectedRadioButton(btnGrp_relationshipToPatient_1));            
        }else{
            insurance.setInsuredRelationship(tf_specify.getText());
        }                
        
        insurance.setInsuranceName(tf_insurance_id.getName());
        insurance.setInsuranceNo(toInteger(tf_insurance_no.getText()));        
        insurance.setInsuranceCompanyName(tf_insurance_company.getText());
        insurance.setRemaining(BigDecimal.valueOf(sp_remaining.getModel().getValue().hashCode()));
        insurance.setInsuranceAddress(tf_insurance_address.getText());
        insurance.setInsuranceMunicipality(tf_insurance_municipality.getText());
        insurance.setInsuranceCity(tf_insurance_city.getText());
        insurance.setInsuranceZip(toInteger(tf_insurance_zip.getText()));
        
        
        patient.register(address, contact, contactPerson, insurance);
    }//GEN-LAST:event_btn_registerActionPerformed

    private void tf_philhealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_philhealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_philhealthActionPerformed

    private void rb_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_maleActionPerformed
        //patient.setGender(this.rb_male.getText());
    }//GEN-LAST:event_rb_maleActionPerformed

    private void rb_mixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_mixedActionPerformed
        //patient.setGender(this.rb_mixed.getText());
    }//GEN-LAST:event_rb_mixedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel admin_level;
    public javax.swing.JLabel admin_name;
    public javax.swing.JPanel body;
    public javax.swing.ButtonGroup btnGrp_gender;
    public javax.swing.ButtonGroup btnGrp_relationshipToPatient_1;
    public javax.swing.ButtonGroup btnGrp_relationshipToPatient_2;
    public javax.swing.JButton btn_back;
    public javax.swing.JButton btn_close;
    public javax.swing.JButton btn_register;
    public javax.swing.JComboBox<String> cmbx_civilStatus;
    public javax.swing.JPanel footer;
    public javax.swing.JPanel header;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel38;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel51;
    public javax.swing.JLabel jLabel52;
    public javax.swing.JLabel jLabel53;
    public javax.swing.JLabel jLabel56;
    public javax.swing.JLabel jLabel57;
    public javax.swing.JLabel jLabel59;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField13;
    public com.toedter.calendar.JDateChooser jd_birthdate;
    public com.toedter.calendar.JDateChooser jd_insured_birthdate;
    public javax.swing.JLabel lbl_specify;
    public javax.swing.JLabel logo;
    public javax.swing.JPanel pnl_address;
    public javax.swing.JPanel pnl_contact;
    public javax.swing.JPanel pnl_contact_person;
    public javax.swing.JPanel pnl_government_mandated;
    public javax.swing.JPanel pnl_insurance_info;
    public javax.swing.JPanel pnl_personalInfo3;
    protected javax.swing.JPanel pnl_primary;
    public javax.swing.JRadioButton rb_child;
    public javax.swing.JRadioButton rb_female;
    public javax.swing.JRadioButton rb_male;
    public javax.swing.JRadioButton rb_mixed;
    public javax.swing.JRadioButton rb_other;
    public javax.swing.JRadioButton rb_self;
    public javax.swing.JRadioButton rb_spouse;
    public javax.swing.JSpinner sp_age;
    public javax.swing.JSpinner sp_remaining;
    public javax.swing.JLabel subModuleHeader;
    public javax.swing.JTextField tf_birthplace;
    public javax.swing.JTextField tf_cellphone;
    public javax.swing.JTextField tf_city;
    public javax.swing.JTextField tf_contact_person_contact;
    public javax.swing.JTextField tf_contact_person_firstname;
    public javax.swing.JTextField tf_contact_person_lastname;
    public javax.swing.JTextField tf_contact_person_middlename;
    public javax.swing.JTextField tf_contact_person_relation;
    public javax.swing.JTextField tf_email;
    public javax.swing.JTextField tf_firstname;
    public javax.swing.JTextField tf_gsis;
    public javax.swing.JTextField tf_insurance_address;
    public javax.swing.JTextField tf_insurance_city;
    public javax.swing.JTextField tf_insurance_company;
    public javax.swing.JTextField tf_insurance_id;
    public javax.swing.JTextField tf_insurance_municipality;
    public javax.swing.JTextField tf_insurance_no;
    public javax.swing.JTextField tf_insurance_zip;
    public javax.swing.JTextField tf_insured_lastname;
    public javax.swing.JTextField tf_insured_middlename;
    public javax.swing.JTextField tf_insured_name;
    public javax.swing.JTextField tf_lastname;
    public javax.swing.JTextField tf_lot;
    public javax.swing.JTextField tf_middlename;
    public javax.swing.JTextField tf_municipality;
    public javax.swing.JTextField tf_nationality;
    public javax.swing.JTextField tf_occupation;
    public javax.swing.JTextField tf_philhealth;
    public javax.swing.JTextField tf_specify;
    public javax.swing.JTextField tf_sss;
    public javax.swing.JTextField tf_telephone;
    public javax.swing.JTextField tf_zip;
    public javax.swing.JPanel window_control;
    // End of variables declaration//GEN-END:variables
}
