/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.core1.core1;
import main.core2.core2;
import main.core2.hmo;
import main.core2.index;

/**
 *
 * @author Joseph
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        admin_level.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        window_control = new javax.swing.JPanel();
        btn_back = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        admin_level = new javax.swing.JLabel();
        admin_name = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        patient_registration = new javax.swing.JPanel();
        btn_registration = new javax.swing.JButton();
        btn_outPatient = new javax.swing.JButton();
        btn_inPatient = new javax.swing.JButton();
        btn_doctorsAppointment = new javax.swing.JButton();
        btn_bedAndLinen = new javax.swing.JButton();
        patient_info = new javax.swing.JPanel();
        btn_outPatientTreatment = new javax.swing.JButton();
        btn_laboratory = new javax.swing.JButton();
        btn_hmo = new javax.swing.JButton();
        btn_scheduler = new javax.swing.JButton();
        btn_discharge = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HMS - Main");
        setExtendedState(6);
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setUndecorated(true);
        setResizable(false);

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setMaximumSize(new java.awt.Dimension(1024, 80));
        header.setMinimumSize(new java.awt.Dimension(1024, 80));
        header.setPreferredSize(new java.awt.Dimension(1024, 110));

        window_control.setOpaque(false);
        window_control.setLayout(new java.awt.GridLayout(1, 0));

        btn_back.setText("<");
        btn_back.setOpaque(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        window_control.add(btn_back);

        btn_close.setText("X");
        btn_close.setOpaque(false);
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        window_control.add(btn_close);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/logo_227x104.png"))); // NOI18N

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        admin_level.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(admin_level);

        admin_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin_name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(admin_name);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 560, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(window_control, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(window_control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        patient_registration.setLayout(new java.awt.GridLayout(2, 3, 4, 4));

        btn_registration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_registration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/people-8x.png"))); // NOI18N
        btn_registration.setText("Registration");
        btn_registration.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_registration.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        patient_registration.add(btn_registration);

        btn_outPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_outPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/beaker-8x.png"))); // NOI18N
        btn_outPatient.setText("Out Patient");
        btn_outPatient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_outPatient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        patient_registration.add(btn_outPatient);

        btn_inPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_inPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/medical-cross-8x.png"))); // NOI18N
        btn_inPatient.setText("In Patient");
        btn_inPatient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_inPatient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        patient_registration.add(btn_inPatient);

        btn_doctorsAppointment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_doctorsAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/calendar-8x.png"))); // NOI18N
        btn_doctorsAppointment.setText("Doctors Appointment");
        btn_doctorsAppointment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_doctorsAppointment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        patient_registration.add(btn_doctorsAppointment);

        btn_bedAndLinen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_bedAndLinen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/task-8x.png"))); // NOI18N
        btn_bedAndLinen.setText("Bed and Linen Management");
        btn_bedAndLinen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_bedAndLinen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        patient_registration.add(btn_bedAndLinen);

        jTabbedPane1.addTab("Core Transaction 1", patient_registration);

        patient_info.setLayout(new java.awt.GridLayout(2, 3, 4, 4));

        btn_outPatientTreatment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_outPatientTreatment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/people-8x.png"))); // NOI18N
        btn_outPatientTreatment.setText("Out Patient Treatment");
        btn_outPatientTreatment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_outPatientTreatment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        patient_info.add(btn_outPatientTreatment);

        btn_laboratory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_laboratory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/beaker-8x.png"))); // NOI18N
        btn_laboratory.setText("Laboratory");
        btn_laboratory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_laboratory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        patient_info.add(btn_laboratory);

        btn_hmo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_hmo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/medical-cross-8x.png"))); // NOI18N
        btn_hmo.setText("HMO and Insurance");
        btn_hmo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_hmo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_hmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hmoActionPerformed(evt);
            }
        });
        patient_info.add(btn_hmo);

        btn_scheduler.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_scheduler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/calendar-8x.png"))); // NOI18N
        btn_scheduler.setText("Surgery Scheduler");
        btn_scheduler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_scheduler.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        patient_info.add(btn_scheduler);

        btn_discharge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_discharge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/task-8x.png"))); // NOI18N
        btn_discharge.setText("Discharge");
        btn_discharge.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_discharge.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        patient_info.add(btn_discharge);

        jTabbedPane1.addTab("Core Transaction 2", patient_info);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Core Transaction 3", jPanel3);

        footer.setBackground(new java.awt.Color(255, 255, 255));
        footer.setMaximumSize(new java.awt.Dimension(1024, 30));
        footer.setMinimumSize(new java.awt.Dimension(1024, 30));
        footer.setPreferredSize(new java.awt.Dimension(1024, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Copyright 2018, All Rights reserved to Developers Team.");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(footerLayout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addGap(279, 279, 279)))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(footerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 483, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_hmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hmoActionPerformed
       hmo hmo = new hmo();
       hmo.setVisible(true);
       hmo.admin_level1.setText(this.admin_level.getText());
       hmo.admin_name1.setText(this.admin_name.getText());
       this.dispose();
    }//GEN-LAST:event_btn_hmoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel admin_level;
    public javax.swing.JLabel admin_name;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_bedAndLinen;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_discharge;
    private javax.swing.JButton btn_doctorsAppointment;
    private javax.swing.JButton btn_hmo;
    private javax.swing.JButton btn_inPatient;
    private javax.swing.JButton btn_laboratory;
    private javax.swing.JButton btn_outPatient;
    private javax.swing.JButton btn_outPatientTreatment;
    private javax.swing.JButton btn_registration;
    private javax.swing.JButton btn_scheduler;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel patient_info;
    private javax.swing.JPanel patient_registration;
    private javax.swing.JPanel window_control;
    // End of variables declaration//GEN-END:variables
}
