/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.core2;

/**
 *
 * @author DelaTorreNelson
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sub_modules = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btn_outPatient = new javax.swing.JButton();
        btn_laboratory = new javax.swing.JButton();
        btn_hmo = new javax.swing.JButton();
        btn_scheduler = new javax.swing.JButton();
        btn_discharge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        sub_modules.setLayout(new java.awt.GridLayout(2, 3, 4, 4));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/logo_227x104.png"))); // NOI18N
        sub_modules.add(logo);

        btn_outPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/people-8x.png"))); // NOI18N
        btn_outPatient.setText("Out Patient Treatment");
        btn_outPatient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_outPatient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sub_modules.add(btn_outPatient);

        btn_laboratory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/beaker-8x.png"))); // NOI18N
        btn_laboratory.setText("Laboratory");
        btn_laboratory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_laboratory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sub_modules.add(btn_laboratory);

        btn_hmo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/medical-cross-8x.png"))); // NOI18N
        btn_hmo.setText("HMO and Insurance");
        btn_hmo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_hmo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sub_modules.add(btn_hmo);

        btn_scheduler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/calendar-8x.png"))); // NOI18N
        btn_scheduler.setText("Surgery Scheduler");
        btn_scheduler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_scheduler.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sub_modules.add(btn_scheduler);

        btn_discharge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons/task-8x.png"))); // NOI18N
        btn_discharge.setText("Discharge");
        btn_discharge.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_discharge.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sub_modules.add(btn_discharge);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sub_modules, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sub_modules, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_discharge;
    public javax.swing.JButton btn_hmo;
    public javax.swing.JButton btn_laboratory;
    public javax.swing.JButton btn_outPatient;
    public javax.swing.JButton btn_scheduler;
    public javax.swing.JLabel logo;
    public javax.swing.JPanel sub_modules;
    // End of variables declaration//GEN-END:variables
}
